openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    API для роботи з контактами: створення, редагування, видалення та отримання списку контактів.
tags:
  - name: Contacts
    description: Operations about users.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://127.0.0.1:3000
  - url: https://hw7-swagger-vym3.onrender.com
paths:
  /contacts:
    get:
      $ref: "../swagger/paths/contacts/get.yaml"
    post:
      $ref: "../swagger/paths/contacts/post.yaml"
  /contacts/{id}:
    get:
      $ref: "../swagger/paths/contacts/{id}/get.yaml"
    patch:
      $ref: "../swagger/paths/contacts/{id}/patch.yaml"
    delete:
      $ref: "../swagger/paths/contacts/{id}/delete.yaml"
  /auth/register:
    post:
      $ref: "../swagger/paths/auth/register.yaml"
  /auth/login:
    post:
      $ref: "../swagger/paths/auth/login.yaml"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
